import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          This is the place where we can do things and place our ads into the work and get consumers get to the click and do the
          things right and do the ads placed in places where consumers are buying things right of the batch. This is your one place to look
          into this is the most valuable places in the world where we can lear about diffrent things that we can do with places are diffrent that what we Think
          randomly selected the body of the content and test which content resonates with the audience you want to target. This will help
          brands to do A/B test and choose the right content for there ads body. This is way we can achive the targeted goal of our campains.
          This way we can find the diffrence between a good ad and a bad ad. This is where we come together and do lot of work together and this way
          we can get the things we have to place in the places that we can leave without. This way we can achive what we want to get from our ads and
          abd unfortunately we have go through the placement option and look around the things and place our ads accordingly. This is the way we have
          to place our ads and this way we can tell which ads is performing well and which ads should we have to put in our places.
        </h1>

        <p className={styles.description}>
          Get started by editing and do some wonderful things with it. This is the case where you can get lot of computional power and
          do lot of work and do nothing about it. This is the place where we can put lot of details and do lot of work and do not possibly
          do a lot with this. This is the thing I can do to achive a lot of work and do lot of work and it will blow your mind. It will help
          our brand to recognise as a band to achive a lot. This is a place where people can book orders and contact with consumers and put
          lot of work to do its thing. It can also setup a business profile to get access extra features and grow the business. This can achive
          set up professional dashboard to get the insights of the profile.
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API. This will help us build the things we want to optimise this
              is the place to do some awesome things that we can do in this place. It will help us to do things like we can prove the
              things we can do to play with the visitors of your website. This is the place where you can do the things I am fortunate
              about but this is the place where we should apply our knowledge with all the things we can. That's why we sould turn things
              all around. Think of the company engagement you are looking for so that we can do the the things we are supposed to do. This
              is a demographic thing that I can use to do things that we have to put on things as soon as possible.
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes! This is a place where you can put your all designs.
              This is the place where I have to put all my work done. This is a place where you put lot of work and do some business
              related work. This is why we have to put lot's of work and we need hard working people to do the work. So this is the place where
              we have to put all of the things. This is the thing we are talking about and this is the place we are going to run all our ads. This
              the place for tropical use of things
            </p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects. This is a place where you can put lot of work done in your places. This is
              thing where you can put lot of work and do the needful and do lot of work. I have to put lot of work In this place to remember the things
              That will shape the future of the world and it will be the place where you can do some magic and get all the things that will get a lot.
              Measure success with page insights and it will helpful to dot he things that can help with share the page outside of everything and do some
              research and do the needful and you will be doing this to place the things to places where the possibilities can be harness. This is the place
              to do the work and do some awesome work. This is the place I will be with the things I will be using to do more. This will be the first thing
              we can use to do this type of things to place it in the right place.
            </p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card}>
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel. This is the place where you can do some helpful work
              and do the things in a beautiful manner. This is the place where  you can place diffrent things and put this thing in a
              place where you can place things that can put in a thing you can put yourselt into. This is a place where you can amplify
              things to place upon. It will be the first thing I will be using to do some heavy work to do and it will do the needful and
              this will help to reduce to use photos to highlight the offerings of a business and you can schedule post to publish later.
              You can draft post for future schedule and do the things we are taught to do so in the marketplace. There are page roles you
              can assign to individual who can manage the page as per there permission alows them to do so. This is where ads come into play
              that we will be helpful to reach more people. This ads will cost less and you can share your page to large audience.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
